In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/rsm08_raw.csv")

In [51]:
df.head()

,"ï»¿""STATISTIC""",Statistic Label,TLIST(M1),Month,C02583V03135,NACE Group,UNIT,VALUE
0,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,45,Motor trades (45),Base Year 2021=100,83.5
1,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,4711,Retail sale in non-specialised stores with foo...,Base Year 2021=100,102.3
2,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,4719,Department stores (4719),Base Year 2021=100,65.1
3,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,4730,Retail sale of automotive fuel (4730),Base Year 2021=100,77.7
4,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,4752,"Retail sale of hardware, paints and glass (4752)",Base Year 2021=100,89.8

In [52]:
df.shape

(11792, 8)

In [53]:
df.columns

Index(['ï»¿"STATISTIC"', 'Statistic Label', 'TLIST(M1)', 'Month',
       'C02583V03135', 'NACE Group', 'UNIT', 'VALUE'],
      dtype='str')

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11792 entries, 0 to 11791
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ï»¿"STATISTIC"   11792 non-null  str
 1   Statistic Label  11792 non-null  str
 2   TLIST(M1)        11792 non-null  int64
 3   Month            11792 non-null  str
 4   C02583V03135     11792 non-null  str
 5   NACE Group       11792 non-null  str
 6   UNIT             11792 non-null  str
 7   VALUE            11220 non-null  float64
dtypes: float64(1), int64(1), str(6)
memory usage: 737.1 KB

In [55]:
df.isna().sum()

ï»¿"STATISTIC"       0
Statistic Label      0
TLIST(M1)            0
Month                0
C02583V03135         0
NACE Group           0
UNIT                 0
VALUE              572
dtype: int64

In [56]:
df["Statistic Label"].unique()

<StringArray>
[                                 'Retail Sales Index Volume Adjusted',
   'Retail Sales Index Volume Adjusted Percentage Change over 1 month',
 'Retail Sales Index Volume Adjusted Percentage Change over 12 months',
                                'Retail Sales Index Volume Unadjusted',
                                   'Retail Sales Index Value Adjusted',
    'Retail Sales Index Value Adjusted Percentage Change over 1 month',
  'Retail Sales Index Value Adjusted Percentage Change over 12 months',
                                 'Retail Sales Index Value Unadjusted']
Length: 8, dtype: str

In [57]:
df["NACE Group"].unique()

<StringArray>
[                                                                            'Motor trades (45)',
    'Retail sale in non-specialised stores with food, beverages or tobacco predominating (4711)',
                                                                      'Department stores (4719)',
                                                         'Retail sale of automotive fuel (4730)',
                                              'Retail sale of hardware, paints and glass (4752)',
                                                  'Retail sale of furniture and lighting (4759)',
                                                                                   'Bars (5630)',
                                                                         'All retail businesses',
                                                    'Motor trades and automotive fuel (45,4730)',
                                        'All retail businesses, excluding motor trades and bars',
                                                 'All retail businesses, excluding motor trades',
                       'All retail businesses, excluding motor trades, automotive fuel and bars',
                                                       'Retail sale of food (4711,4721 to 4729)',
            'Retail sale of non food products, excluding motor trades, automotive fuel and bars',
               'Retail sale of food, beverages and tobacco in specialised stores (4721 to 4729)',
                              'Retail sale of household equipment (4741 to 4743,4752,4754,4759)',
                                           'Retail sale of electrical goods (4741 to 4743,4754)',
                               'Retail sale of textiles, clothing and footwear (4751,4771,4772)',
 'Retail sale of books, newspapers, stationery and other goods (4753,4761 to 4765,4776 to 4778)',
                                           'Other retail sales (4753,4763 to 4765,4776 to 4778)',
                                   'Retail sale of books, newspapers and stationery (4761,4762)',
                   'Retail sale of pharmaceutical, medical and cosmetic articles (4773 to 4775)']
Length: 22, dtype: str

In [58]:
df["NACE Group"].nunique()

22

In [59]:
df["Month"].min()

'2021 April'

In [60]:
df["Month"].max()

'2026 May'

In [61]:
df["UNIT"].unique()

<StringArray>
['Base Year 2021=100', '%']
Length: 2, dtype: str

In [62]:
df[df["VALUE"].isna()].head(20)

,"ï»¿""STATISTIC""",Statistic Label,TLIST(M1),Month,C02583V03135,NACE Group,UNIT,VALUE
1474,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,45,Motor trades (45),%,NaN
1475,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,4711,Retail sale in non-specialised stores with foo...,%,NaN
1476,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,4719,Department stores (4719),%,NaN
1477,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,4730,Retail sale of automotive fuel (4730),%,NaN
1478,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,4752,"Retail sale of hardware, paints and glass (4752)",%,NaN
1479,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,4759,Retail sale of furniture and lighting (4759),%,NaN
1480,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,5630,Bars (5630),%,NaN
1481,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,V3970,All retail businesses,%,NaN
1482,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,V3980,"Motor trades and automotive fuel (45,4730)",%,NaN
1483,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1310,"All retail businesses, excluding motor trades ...",%,NaN
1484,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1320,"All retail businesses, excluding motor trades",%,NaN
1485,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1330,"All retail businesses, excluding motor trades,...",%,NaN
1486,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1340,"Retail sale of food (4711,4721 to 4729)",%,NaN
1487,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1350,"Retail sale of non food products, excluding mo...",%,NaN
1488,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1360,"Retail sale of food, beverages and tobacco in ...",%,NaN
1489,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1370,Retail sale of household equipment (4741 to 47...,%,NaN
1490,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1380,"Retail sale of electrical goods (4741 to 4743,...",%,NaN
1491,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1390,"Retail sale of textiles, clothing and footwear...",%,NaN
1492,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1400,"Retail sale of books, newspapers, stationery a...",%,NaN
1493,RSM08C05,Retail Sales Index Volume Adjusted Percentage ...,202101,2021 January,X1410,"Other retail sales (4753,4763 to 4765,4776 to ...",%,NaN

In [63]:
df[df["VALUE"].isna()]["Statistic Label"].value_counts()

Statistic Label
Retail Sales Index Volume Adjusted Percentage Change over 12 months    264
Retail Sales Index Value Adjusted Percentage Change over 12 months     264
Retail Sales Index Volume Adjusted Percentage Change over 1 month       22
Retail Sales Index Value Adjusted Percentage Change over 1 month        22
Name: count, dtype: int64

In [64]:
df[df["VALUE"].isna()]["NACE Group"].value_counts()

NACE Group
Motor trades (45)                                                                                26
Retail sale in non-specialised stores with food, beverages or tobacco predominating (4711)       26
Department stores (4719)                                                                         26
Retail sale of automotive fuel (4730)                                                            26
Retail sale of hardware, paints and glass (4752)                                                 26
Retail sale of furniture and lighting (4759)                                                     26
Bars (5630)                                                                                      26
All retail businesses                                                                            26
Motor trades and automotive fuel (45,4730)                                                       26
All retail businesses, excluding motor trades and bars                                           26
All retail businesses, excluding motor trades                                                    26
All retail businesses, excluding motor trades, automotive fuel and bars                          26
Retail sale of food (4711,4721 to 4729)                                                          26
Retail sale of non food products, excluding motor trades, automotive fuel and bars               26
Retail sale of food, beverages and tobacco in specialised stores (4721 to 4729)                  26
Retail sale of household equipment (4741 to 4743,4752,4754,4759)                                 26
Retail sale of electrical goods (4741 to 4743,4754)                                              26
Retail sale of textiles, clothing and footwear (4751,4771,4772)                                  26
Retail sale of books, newspapers, stationery and other goods (4753,4761 to 4765,4776 to 4778)    26
Other retail sales (4753,4763 to 4765,4776 to 4778)                                              26
Retail sale of books, newspapers and stationery (4761,4762)                                      26
Retail sale of pharmaceutical, medical and cosmetic articles (4773 to 4775)                      26
Name: count, dtype: int64

In [65]:
df[df["VALUE"].isna()]["Month"].value_counts().sort_index()

Month
2021 April        44
2021 August       44
2021 December     44
2021 February     44
2021 January      88
2021 July         44
2021 June         44
2021 March        44
2021 May          44
2021 November     44
2021 October      44
2021 September    44
Name: count, dtype: int64

In [66]:
df["Month"].min()

'2021 April'

In [67]:
df["Month"].max()

'2026 May'

In [68]:
df["Month"].nunique()

67

In [69]:
df["Month"].nunique()

67

In [70]:
df.duplicated().sum()

np.int64(0)

In [3]:
df.duplicated(
    subset=[
        "Statistic Label",
        "Month",
        "NACE Group",
        "UNIT"
    ]
).sum()

np.int64(0)

#Let's focus on What is needed for the main project and clean clear data analytics

In [4]:
df = pd.read_csv(
    "../data/raw/rsm08_raw.csv",
    encoding="utf-8-sig"
)

print(df.columns.tolist())

['ï»¿"STATISTIC"', 'Statistic Label', 'TLIST(M1)', 'Month', 'C02583V03135', 'NACE Group', 'UNIT', 'VALUE']

In [5]:
df.columns = df.columns.str.replace(
    'ï»¿"',
    '',
    regex=False
)

df.columns = df.columns.str.replace(
    '"',
    '',
    regex=False
)

print(df.columns.tolist())

['STATISTIC', 'Statistic Label', 'TLIST(M1)', 'Month', 'C02583V03135', 'NACE Group', 'UNIT', 'VALUE']

#Now find our main retail series

In [6]:
main_retail = df[
    (df["STATISTIC"] == "RSM08C04") &
    (df["NACE Group"] == "All retail businesses") &
    (df["UNIT"] == "Base Year 2021=100")
]

main_retail.head()

,STATISTIC,Statistic Label,TLIST(M1),Month,C02583V03135,NACE Group,UNIT,VALUE
7,RSM08C04,Retail Sales Index Volume Adjusted,202101,2021 January,V3970,All retail businesses,Base Year 2021=100,80.0
29,RSM08C04,Retail Sales Index Volume Adjusted,202102,2021 February,V3970,All retail businesses,Base Year 2021=100,89.8
51,RSM08C04,Retail Sales Index Volume Adjusted,202103,2021 March,V3970,All retail businesses,Base Year 2021=100,90.1
73,RSM08C04,Retail Sales Index Volume Adjusted,202104,2021 April,V3970,All retail businesses,Base Year 2021=100,90.4
95,RSM08C04,Retail Sales Index Volume Adjusted,202105,2021 May,V3970,All retail businesses,Base Year 2021=100,100.6

In [7]:
main_retail.shape

(67, 8)

In [8]:
main_retail["VALUE"].isna().sum()

np.int64(0)

look at the actual time series

In [9]:
main_retail[
    ["Month", "VALUE"]
].head(10)

              Month  VALUE
7      2021 January   80.0
29    2021 February   89.8
51       2021 March   90.1
73       2021 April   90.4
95         2021 May  100.6
117       2021 June  106.9
139       2021 July  105.4
161     2021 August  104.1
183  2021 September  105.1
205    2021 October  109.7

In [10]:
main_retail[
    ["Month", "VALUE"]
].tail(10)

              Month  VALUE
1261   2025 October  114.7
1283  2025 November  115.1
1305  2025 December  114.7
1327   2026 January  116.6
1349  2026 February  115.8
1371     2026 March  115.2
1393     2026 April  115.1
1415       2026 May  115.8
1437      2026 June  116.4
1459      2026 July  118.0

Create  a clean table now!

In [11]:
retail_clean = main_retail[
    ["Month", "VALUE"]
].copy()

retail_clean

              Month  VALUE
7      2021 January   80.0
29    2021 February   89.8
51       2021 March   90.1
73       2021 April   90.4
95         2021 May  100.6
...             ...    ...
1371     2026 March  115.2
1393     2026 April  115.1
1415       2026 May  115.8
1437      2026 June  116.4
1459      2026 July  118.0

[67 rows x 2 columns]

In [12]:
retail_clean = main_retail[["Month", "VALUE"]].copy()

retail_clean = retail_clean.reset_index(drop=True)

retail_clean

            Month  VALUE
0    2021 January   80.0
1   2021 February   89.8
2      2021 March   90.1
3      2021 April   90.4
4        2021 May  100.6
..            ...    ...
62     2026 March  115.2
63     2026 April  115.1
64       2026 May  115.8
65      2026 June  116.4
66      2026 July  118.0

[67 rows x 2 columns]

In [13]:
retail_clean = retail_clean.rename(
    columns={
        "Month": "date",
        "VALUE": "retail_sales_index"
    }
)

retail_clean.head()

            date  retail_sales_index
0   2021 January                80.0
1  2021 February                89.8
2     2021 March                90.1
3     2021 April                90.4
4       2021 May               100.6

Format the date in standard format

In [14]:
retail_clean["date"] = pd.to_datetime(
    retail_clean["date"],
    format="%Y %B"
)

In [15]:
retail_clean.head()

        date  retail_sales_index
0 2021-01-01                80.0
1 2021-02-01                89.8
2 2021-03-01                90.1
3 2021-04-01                90.4
4 2021-05-01               100.6


reset the index

In [16]:
retail_clean = retail_clean.reset_index(drop=True)

In [17]:
retail_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                67 non-null     datetime64[us]
 1   retail_sales_index  67 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 1.2 KB

Save the processed dataset

In [18]:
from pathlib import Path

output_path = Path("Data/processed")
output_path.mkdir(parents=True, exist_ok=True)

retail_clean.to_csv(
    output_path / "rsm08_retail_monthly.csv",
    index=False
)

In [19]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

output_path = PROJECT_ROOT / "Data" / "processed"
output_path.mkdir(parents=True, exist_ok=True)

retail_clean.to_csv(
    output_path / "rsm08_retail_monthly.csv",
    index=False
)

In [20]:
retail_clean[
    retail_clean["date"].between(
        "2021-09-01",
        "2021-11-01"
    )
]

         date  retail_sales_index
8  2021-09-01               105.1
9  2021-10-01               109.7
10 2021-11-01               111.8

In [21]:
retail_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                67 non-null     datetime64[us]
 1   retail_sales_index  67 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 1.2 KB

In [22]:
print("Shape:", retail_clean.shape)

print("\nColumns:")
print(retail_clean.columns.tolist())

print("\nData types:")
print(retail_clean.dtypes)

print("\nMissing values:")
print(retail_clean.isna().sum())

Shape: (67, 2)

Columns:
['date', 'retail_sales_index']

Data types:
date                  datetime64[us]
retail_sales_index           float64
dtype: object

Missing values:
date                  0
retail_sales_index    0
dtype: int64

## Calculate our own retail growth metrics

In [23]:
retail_clean["mom_growth_pct"] = (
    retail_clean["retail_sales_index"]
    .pct_change() * 100
)

retail_clean.head(10) #this calculates the (current month - previous month) / previous month * 100 to get the percentage change from the previous month to the current month.

        date  retail_sales_index  mom_growth_pct
0 2021-01-01                80.0             NaN
1 2021-02-01                89.8       12.250000
2 2021-03-01                90.1        0.334076
3 2021-04-01                90.4        0.332963
4 2021-05-01               100.6       11.283186
5 2021-06-01               106.9        6.262425
6 2021-07-01               105.4       -1.403181
7 2021-08-01               104.1       -1.233397
8 2021-09-01               105.1        0.960615
9 2021-10-01               109.7        4.376784

In [24]:
retail_clean["yoy_growth_pct"] = (
    retail_clean["retail_sales_index"]
    .pct_change(periods=12) * 100
)

retail_clean.head(15)

         date  retail_sales_index  mom_growth_pct  yoy_growth_pct
0  2021-01-01                80.0             NaN             NaN
1  2021-02-01                89.8       12.250000             NaN
2  2021-03-01                90.1        0.334076             NaN
3  2021-04-01                90.4        0.332963             NaN
4  2021-05-01               100.6       11.283186             NaN
5  2021-06-01               106.9        6.262425             NaN
6  2021-07-01               105.4       -1.403181             NaN
7  2021-08-01               104.1       -1.233397             NaN
8  2021-09-01               105.1        0.960615             NaN
9  2021-10-01               109.7        4.376784             NaN
10 2021-11-01               111.8        1.914312             NaN
11 2021-12-01               104.1       -6.887299             NaN
12 2022-01-01               100.2       -3.746398       25.250000
13 2022-02-01               102.8        2.594810       14.476615
14 2022-03-01               105.3        2.431907       16.870144

In [25]:
retail_clean.head(15)

         date  retail_sales_index  mom_growth_pct  yoy_growth_pct
0  2021-01-01                80.0             NaN             NaN
1  2021-02-01                89.8       12.250000             NaN
2  2021-03-01                90.1        0.334076             NaN
3  2021-04-01                90.4        0.332963             NaN
4  2021-05-01               100.6       11.283186             NaN
5  2021-06-01               106.9        6.262425             NaN
6  2021-07-01               105.4       -1.403181             NaN
7  2021-08-01               104.1       -1.233397             NaN
8  2021-09-01               105.1        0.960615             NaN
9  2021-10-01               109.7        4.376784             NaN
10 2021-11-01               111.8        1.914312             NaN
11 2021-12-01               104.1       -6.887299             NaN
12 2022-01-01               100.2       -3.746398       25.250000
13 2022-02-01               102.8        2.594810       14.476615
14 2022-03-01               105.3        2.431907       16.870144

## CSO-vs-our-calculation validation step

In [26]:
growth_series = df[
    (df["NACE Group"] == "All retail businesses") &
    (df["UNIT"] == "%")
].copy()

growth_series[
    ["STATISTIC", "Statistic Label"]
].drop_duplicates()

     STATISTIC                                    Statistic Label
1481  RSM08C05  Retail Sales Index Volume Adjusted Percentage ...
2955  RSM08C06  Retail Sales Index Volume Adjusted Percentage ...
7377  RSM08C07  Retail Sales Index Value Adjusted Percentage C...
8851  RSM08C08  Retail Sales Index Value Adjusted Percentage C...

In [27]:
official_growth = df[
    (df["NACE Group"] == "All retail businesses") &
    (df["UNIT"] == "%") &
    (df["STATISTIC"].isin(["RSM08C05", "RSM08C06"]))
].copy()

official_growth = official_growth[
    ["STATISTIC", "Month", "VALUE"]
]

official_growth.head(15)

     STATISTIC           Month  VALUE
1481  RSM08C05    2021 January    NaN
1503  RSM08C05   2021 February   12.3
1525  RSM08C05      2021 March    0.3
1547  RSM08C05      2021 April    0.3
1569  RSM08C05        2021 May   11.3
1591  RSM08C05       2021 June    6.2
1613  RSM08C05       2021 July   -1.3
1635  RSM08C05     2021 August   -1.3
1657  RSM08C05  2021 September    1.0
1679  RSM08C05    2021 October    4.4
1701  RSM08C05   2021 November    1.9
1723  RSM08C05   2021 December   -7.0
1745  RSM08C05    2022 January   -3.7
1767  RSM08C05   2022 February    2.6
1789  RSM08C05      2022 March    2.5

In [28]:
official_growth.shape

(134, 3)

In [29]:
official_growth.head(15)

     STATISTIC           Month  VALUE
1481  RSM08C05    2021 January    NaN
1503  RSM08C05   2021 February   12.3
1525  RSM08C05      2021 March    0.3
1547  RSM08C05      2021 April    0.3
1569  RSM08C05        2021 May   11.3
1591  RSM08C05       2021 June    6.2
1613  RSM08C05       2021 July   -1.3
1635  RSM08C05     2021 August   -1.3
1657  RSM08C05  2021 September    1.0
1679  RSM08C05    2021 October    4.4
1701  RSM08C05   2021 November    1.9
1723  RSM08C05   2021 December   -7.0
1745  RSM08C05    2022 January   -3.7
1767  RSM08C05   2022 February    2.6
1789  RSM08C05      2022 March    2.5

In [30]:
official_growth.shape

(134, 3)

In [31]:
official_growth_wide = official_growth.pivot(
    index="Month",
    columns="STATISTIC",
    values="VALUE"
).reset_index()

official_growth_wide

STATISTIC          Month  RSM08C05  RSM08C06
0             2021 April       0.3       NaN
1            2021 August      -1.3       NaN
2          2021 December      -7.0       NaN
3          2021 February      12.3       NaN
4           2021 January       NaN       NaN
..                   ...       ...       ...
62          2026 January       1.6       3.2
63             2026 July       1.3       2.2
64             2026 June       0.5       0.9
65            2026 March      -0.5       0.9
66              2026 May       0.6       1.0

[67 rows x 3 columns]

In [32]:
official_growth_wide = official_growth_wide.rename(
    columns={
        "RSM08C05": "cso_mom_growth_pct",
        "RSM08C06": "cso_yoy_growth_pct"
    }
)

official_growth_wide.head(15)

STATISTIC           Month  cso_mom_growth_pct  cso_yoy_growth_pct
0              2021 April                 0.3                 NaN
1             2021 August                -1.3                 NaN
2           2021 December                -7.0                 NaN
3           2021 February                12.3                 NaN
4            2021 January                 NaN                 NaN
5               2021 July                -1.3                 NaN
6               2021 June                 6.2                 NaN
7              2021 March                 0.3                 NaN
8                2021 May                11.3                 NaN
9           2021 November                 1.9                 NaN
10           2021 October                 4.4                 NaN
11         2021 September                 1.0                 NaN
12             2022 April                 0.8                17.5
13            2022 August                 1.4                 3.6
14          2022 December                 2.1                 7.5

In [33]:
official_growth_wide["date"] = pd.to_datetime(
    official_growth_wide["Month"],
    format="%Y %B"
)

official_growth_wide = official_growth_wide.drop(
    columns=["Month"]
)

official_growth_wide = official_growth_wide.sort_values("date")

official_growth_wide.reset_index(drop=True, inplace=True)

official_growth_wide.head(15)

STATISTIC  cso_mom_growth_pct  cso_yoy_growth_pct       date
0                         NaN                 NaN 2021-01-01
1                        12.3                 NaN 2021-02-01
2                         0.3                 NaN 2021-03-01
3                         0.3                 NaN 2021-04-01
4                        11.3                 NaN 2021-05-01
5                         6.2                 NaN 2021-06-01
6                        -1.3                 NaN 2021-07-01
7                        -1.3                 NaN 2021-08-01
8                         1.0                 NaN 2021-09-01
9                         4.4                 NaN 2021-10-01
10                        1.9                 NaN 2021-11-01
11                       -7.0                 NaN 2021-12-01
12                       -3.7                25.3 2022-01-01
13                        2.6                14.4 2022-02-01
14                        2.5                16.9 2022-03-01

merge it with our calculation

In [34]:
validation = retail_clean.merge(
    official_growth_wide,
    on="date",
    how="left"
)

validation.head(15)

,date,retail_sales_index,mom_growth_pct,yoy_growth_pct,cso_mom_growth_pct,cso_yoy_growth_pct
0,2021-01-01,80.0,NaN,NaN,NaN,NaN
1,2021-02-01,89.8,12.250000,NaN,12.3,NaN
2,2021-03-01,90.1,0.334076,NaN,0.3,NaN
3,2021-04-01,90.4,0.332963,NaN,0.3,NaN
4,2021-05-01,100.6,11.283186,NaN,11.3,NaN
5,2021-06-01,106.9,6.262425,NaN,6.2,NaN
6,2021-07-01,105.4,-1.403181,NaN,-1.3,NaN
7,2021-08-01,104.1,-1.233397,NaN,-1.3,NaN
8,2021-09-01,105.1,0.960615,NaN,1.0,NaN
9,2021-10-01,109.7,4.376784,NaN,4.4,NaN
10,2021-11-01,111.8,1.914312,NaN,1.9,NaN
11,2021-12-01,104.1,-6.887299,NaN,-7.0,NaN
12,2022-01-01,100.2,-3.746398,25.250000,-3.7,25.3
13,2022-02-01,102.8,2.594810,14.476615,2.6,14.4
14,2022-03-01,105.3,2.431907,16.870144,2.5,16.9

In [35]:
validation["mom_difference"] = (
    validation["mom_growth_pct"]
    - validation["cso_mom_growth_pct"]
)

validation["yoy_difference"] = (
    validation["yoy_growth_pct"]
    - validation["cso_yoy_growth_pct"]
)

validation.head(15)

,date,retail_sales_index,mom_growth_pct,yoy_growth_pct,cso_mom_growth_pct,cso_yoy_growth_pct,mom_difference,yoy_difference
0,2021-01-01,80.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,89.8,12.250000,NaN,12.3,NaN,-0.050000,NaN
2,2021-03-01,90.1,0.334076,NaN,0.3,NaN,0.034076,NaN
3,2021-04-01,90.4,0.332963,NaN,0.3,NaN,0.032963,NaN
4,2021-05-01,100.6,11.283186,NaN,11.3,NaN,-0.016814,NaN
5,2021-06-01,106.9,6.262425,NaN,6.2,NaN,0.062425,NaN
6,2021-07-01,105.4,-1.403181,NaN,-1.3,NaN,-0.103181,NaN
7,2021-08-01,104.1,-1.233397,NaN,-1.3,NaN,0.066603,NaN
8,2021-09-01,105.1,0.960615,NaN,1.0,NaN,-0.039385,NaN
9,2021-10-01,109.7,4.376784,NaN,4.4,NaN,-0.023216,NaN
10,2021-11-01,111.8,1.914312,NaN,1.9,NaN,0.014312,NaN
11,2021-12-01,104.1,-6.887299,NaN,-7.0,NaN,0.112701,NaN
12,2022-01-01,100.2,-3.746398,25.250000,-3.7,25.3,-0.046398,-0.050000
13,2022-02-01,102.8,2.594810,14.476615,2.6,14.4,-0.005190,0.076615
14,2022-03-01,105.3,2.431907,16.870144,2.5,16.9,-0.068093,-0.029856

check the maximum difference

In [36]:
validation["mom_difference"].abs().max()

np.float64(0.11270125223613014)

In [37]:
validation["yoy_difference"].abs().max()

np.float64(0.10972871842845744)

check the average difference

In [38]:
validation["mom_difference"].abs().mean()

np.float64(0.03386096272604514)

In [39]:
validation["yoy_difference"].abs().mean()

np.float64(0.03790584092166025)

final validation test , make our comparison cleaner by rounding our calculations to one decimal point

In [40]:
validation["mom_match"] = (
    validation["mom_growth_pct"].round(1)
    == validation["cso_mom_growth_pct"]
)

validation["yoy_match"] = (
    validation["yoy_growth_pct"].round(1)
    == validation["cso_yoy_growth_pct"]
)

In [41]:
validation["mom_match"].value_counts(dropna=False)

mom_match
True     48
False    19
Name: count, dtype: int64

In [42]:
validation["yoy_match"].value_counts(dropna=False)

yoy_match
True     38
False    29
Name: count, dtype: int64

In [43]:
mom_mismatches = validation[
    validation["mom_match"] == False
][
    [
        "date",
        "retail_sales_index",
        "mom_growth_pct",
        "cso_mom_growth_pct",
        "mom_difference"
    ]
]

mom_mismatches

,date,retail_sales_index,mom_growth_pct,cso_mom_growth_pct,mom_difference
0,2021-01-01,80.0,NaN,NaN,NaN
5,2021-06-01,106.9,6.262425,6.2,0.062425
6,2021-07-01,105.4,-1.403181,-1.3,-0.103181
7,2021-08-01,104.1,-1.233397,-1.3,0.066603
11,2021-12-01,104.1,-6.887299,-7.0,0.112701
14,2022-03-01,105.3,2.431907,2.5,-0.068093
15,2022-04-01,106.2,0.854701,0.8,0.054701
17,2022-06-01,108.6,2.646503,2.7,-0.053497
24,2023-01-01,108.9,-2.680965,-2.6,-0.080965
29,2023-06-01,113.2,0.443656,0.5,-0.056344
33,2023-10-01,111.0,-0.359066,-0.3,-0.059066
37,2024-02-01,112.4,-0.881834,-0.8,-0.081834
39,2024-04-01,112.2,-1.837270,-1.9,0.062730
44,2024-09-01,111.5,0.450450,0.4,0.050450
51,2025-04-01,115.6,1.225919,1.3,-0.074081
52,2025-05-01,114.6,-0.865052,-0.8,-0.065052
59,2025-12-01,114.7,-0.347524,-0.4,0.052476
60,2026-01-01,116.6,1.656495,1.6,0.056495
66,2026-07-01,118.0,1.374570,1.3,0.074570

In [44]:
yoy_mismatches = validation[
    validation["yoy_match"] == False
][
    [
        "date",
        "retail_sales_index",
        "yoy_growth_pct",
        "cso_yoy_growth_pct",
        "yoy_difference"
    ]
]

yoy_mismatches

,date,retail_sales_index,yoy_growth_pct,cso_yoy_growth_pct,yoy_difference
0,2021-01-01,80.0,NaN,NaN,NaN
1,2021-02-01,89.8,NaN,NaN,NaN
2,2021-03-01,90.1,NaN,NaN,NaN
3,2021-04-01,90.4,NaN,NaN,NaN
4,2021-05-01,100.6,NaN,NaN,NaN
5,2021-06-01,106.9,NaN,NaN,NaN
6,2021-07-01,105.4,NaN,NaN,NaN
7,2021-08-01,104.1,NaN,NaN,NaN
8,2021-09-01,105.1,NaN,NaN,NaN
9,2021-10-01,109.7,NaN,NaN,NaN
10,2021-11-01,111.8,NaN,NaN,NaN
11,2021-12-01,104.1,NaN,NaN,NaN
12,2022-01-01,100.2,25.250000,25.3,-0.050000
13,2022-02-01,102.8,14.476615,14.4,0.076615
16,2022-05-01,105.8,5.168986,5.1,0.068986
17,2022-06-01,108.6,1.590271,1.7,-0.109729
18,2022-07-01,106.3,0.853890,0.8,0.053890
26,2023-03-01,112.2,6.552707,6.5,0.052707
27,2023-04-01,111.8,5.273070,5.2,0.073070
33,2023-10-01,111.0,0.543478,0.6,-0.056522
34,2023-11-01,113.6,3.649635,3.7,-0.050365
40,2024-05-01,112.5,-0.177462,-0.1,-0.077462
42,2024-07-01,111.6,0.359712,0.3,0.059712
43,2024-08-01,111.0,-2.460457,-2.4,-0.060457
49,2025-02-01,114.5,1.868327,1.8,0.068327
54,2025-07-01,115.4,3.405018,3.5,-0.094982
55,2025-08-01,115.2,3.783784,3.7,0.083784
58,2025-11-01,115.1,2.220249,2.3,-0.079751
66,2026-07-01,118.0,2.253033,2.2,0.053033

In [45]:
validation_valid = validation[
    validation["cso_mom_growth_pct"].notna()
].copy()

validation_valid["mom_difference"] = (
    validation_valid["mom_growth_pct"]
    - validation_valid["cso_mom_growth_pct"]
)

validation_yoy_valid = validation[
    validation["cso_yoy_growth_pct"].notna()
].copy()

validation_yoy_valid["yoy_difference"] = (
    validation_yoy_valid["yoy_growth_pct"]
    - validation_yoy_valid["cso_yoy_growth_pct"]
)

In [46]:
print(
    "Maximum MoM difference:",
    validation_valid["mom_difference"].abs().max()
)

print(
    "Maximum YoY difference:",
    validation_yoy_valid["yoy_difference"].abs().max()
)

Maximum MoM difference: 0.11270125223613014
Maximum YoY difference: 0.10972871842845744

In [47]:
validation_valid["mom_within_tolerance"] = (
    validation_valid["mom_difference"].abs() <= 0.11
)

validation_yoy_valid["yoy_within_tolerance"] = (
    validation_yoy_valid["yoy_difference"].abs() <= 0.11
)

In [48]:
print(
    validation_valid["mom_within_tolerance"].value_counts()
)

print(
    validation_yoy_valid["yoy_within_tolerance"].value_counts()
)

mom_within_tolerance
True     65
False     1
Name: count, dtype: int64
yoy_within_tolerance
True    55
Name: count, dtype: int64

In [49]:
validation_valid[
    validation_valid["mom_within_tolerance"] == False
][
    [
        "date",
        "retail_sales_index",
        "mom_growth_pct",
        "cso_mom_growth_pct",
        "mom_difference"
    ]
]

,date,retail_sales_index,mom_growth_pct,cso_mom_growth_pct,mom_difference
11,2021-12-01,104.1,-6.887299,-7.0,0.112701

In [50]:
validation_valid[
    validation_valid["mom_difference"].between(0.11, 0.12)
][
    [
        "date",
        "mom_growth_pct",
        "cso_mom_growth_pct",
        "mom_difference"
    ]
]

         date  mom_growth_pct  cso_mom_growth_pct  mom_difference
11 2021-12-01       -6.887299                -7.0        0.112701

In [51]:
validation_valid["mom_difference"].max()

np.float64(0.11270125223613014)

In [52]:
validation_valid["mom_difference"].describe()

count    66.000000
mean      0.000810
std       0.043170
min      -0.103181
25%      -0.021946
50%       0.000000
75%       0.033153
max       0.112701
Name: mom_difference, dtype: float64

In [53]:
print("MoM average absolute difference:",
      validation_valid["mom_difference"].abs().mean())

print("MoM maximum absolute difference:",
      validation_valid["mom_difference"].abs().max())

print("YoY average absolute difference:",
      validation_yoy_valid["yoy_difference"].abs().mean())

print("YoY maximum absolute difference:",
      validation_yoy_valid["yoy_difference"].abs().max())

MoM average absolute difference: 0.03386096272604514
MoM maximum absolute difference: 0.11270125223613014
YoY average absolute difference: 0.03790584092166025
YoY maximum absolute difference: 0.10972871842845744

In [54]:
retail_final = validation[
    [
        "date",
        "retail_sales_index",
        "mom_growth_pct",
        "yoy_growth_pct"
    ]
].copy()

retail_final.to_csv(
    "../data/processed/rsm08_retail_validated.csv",
    index=False
)

print("Saved:", "../data/processed/rsm08_retail_validated.csv")
print("Rows:", len(retail_final))
print("Columns:", retail_final.columns.tolist())

Saved: ../data/processed/rsm08_retail_validated.csv
Rows: 67
Columns: ['date', 'retail_sales_index', 'mom_growth_pct', 'yoy_growth_pct']