In [1]:
import pandas as pd

xls = pd.ExcelFile(
    "../data/raw/cbi_mortgage_arrears_raw.xlsx"
)

print(xls.sheet_names)

['Cover_Tab', 'Notes_Tab', 'Table 1 - PDH', 'Table 2 - BTL', 'Table 3 - PDH Bank & Non-Bank', 'Table 4 - BTL Bank & Non-Bank', 'Table 5 - Borrower Engagement', 'Master Data (1)', 'Master Data (2) -Borrower Co-op']

In [2]:
arrears_pdh = pd.read_excel(
    "../data/raw/cbi_mortgage_arrears_raw.xlsx",
    sheet_name="Table 1 - PDH",
    header=None
)

print(arrears_pdh.shape)
arrears_pdh.head(20)

(49, 9)

f:\Irish_Financial_Intelligence\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

,0,1,2,3,4,5,6,7,8
0,Use the slicers to add or change the view of t...,NaN,Table 1: PDH Overview,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Format,PDH,NaN,NaN,NaN,NaN,NaN
2,[Hold CTRL and Click for multiple selctions],NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cover_Tab
3,NaN,NaN,Sum of Amt,NaN,Column Labels,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2025-03-31 00:00:00,2025-06-30 00:00:00,2025-09-30 00:00:00,2025-12-31 00:00:00,2026-03-31 00:00:00
5,NaN,NaN,Row Labels,Row,Number,Number,Number,Number,Number
6,NaN,NaN,Total Outstanding,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,1,Outstanding Mortgages: Total mortgage loan acc...,699890,698335,698933,699968,698459
8,NaN,NaN,Arrears,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,2,Arrears: Total mortgage accounts in arrears,40337,37750,36106,36253,34996
10,NaN,NaN,3,Arrears: Total mortgage accounts in arrears - ...,14455,13167,12327,13596,13694
11,NaN,NaN,4,Arrears: Total mortgage accounts in arrears - ...,3345,3123,3013,2952,2681
12,NaN,NaN,6,Arrears: Total mortgage accounts in arrears - ...,3769,3416,3199,2998,2814
13,NaN,NaN,7,Arrears: Total mortgage accounts in arrears - ...,4136,3867,3522,3285,3040
14,NaN,NaN,9,Arrears: Total mortgage accounts in arrears - ...,5484,5398,5196,5062,4737
15,NaN,NaN,10,Arrears: Total mortgage accounts in arrears - ...,4919,4596,4563,4262,4013
16,NaN,NaN,11,Arrears: Total mortgage accounts in arrears - ...,4229,4183,4286,4098,4017
17,NaN,NaN,Legal Status of Accounts in Arrears,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,12,No Formal Demand,25467,23235,21270,21581,20575
19,NaN,NaN,13,Formal Demand Issued,5425,5097,5409,5248,5024

In [3]:
for i in range(20):
    print(i, arrears_pdh.iloc[i].tolist())

0 ['Use the slicers to add or change the view of the data', np.float64(nan), 'Table 1: PDH Overview', nan, nan, nan, nan, nan, nan]
1 [nan, np.float64(nan), 'Format', 'PDH', nan, nan, nan, nan, nan]
2 ['[Hold CTRL and Click for multiple selctions]', np.float64(nan), nan, nan, nan, nan, nan, nan, 'Cover_Tab']
3 [nan, np.float64(nan), 'Sum of Amt', nan, 'Column Labels', nan, nan, nan, nan]
4 [nan, np.float64(nan), nan, nan, datetime.datetime(2025, 3, 31, 0, 0), datetime.datetime(2025, 6, 30, 0, 0), datetime.datetime(2025, 9, 30, 0, 0), datetime.datetime(2025, 12, 31, 0, 0), datetime.datetime(2026, 3, 31, 0, 0)]
5 [nan, np.float64(nan), 'Row Labels', 'Row', 'Number', 'Number', 'Number', 'Number', 'Number']
6 [nan, np.float64(nan), 'Total Outstanding', nan, nan, nan, nan, nan, nan]
7 [nan, np.float64(nan), 1, 'Outstanding Mortgages: Total mortgage loan accounts outstanding', 699890, 698335, 698933, 699968, 698459]
8 [nan, np.float64(nan), 'Arrears', nan, nan, nan, nan, nan, nan]
9 [nan, np.float64(nan), 2, 'Arrears: Total mortgage accounts in arrears', 40337, 37750, 36106, 36253, 34996]
10 [nan, np.float64(nan), 3, 'Arrears: Total mortgage accounts in arrears - up to 90 days', 14455, 13167, 12327, 13596, 13694]
11 [nan, np.float64(nan), 4, 'Arrears: Total mortgage accounts in arrears - 91 to 180 days', 3345, 3123, 3013, 2952, 2681]
12 [nan, np.float64(nan), 6, 'Arrears: Total mortgage accounts in arrears - 181 to 365 days', 3769, 3416, 3199, 2998, 2814]
13 [nan, np.float64(nan), 7, 'Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS)', 4136, 3867, 3522, 3285, 3040]
14 [nan, np.float64(nan), 9, 'Arrears: Total mortgage accounts in arrears - 2 to 5 yrs', 5484, 5398, 5196, 5062, 4737]
15 [nan, np.float64(nan), 10, 'Arrears: Total mortgage accounts in arrears - 5 to 10 yrs', 4919, 4596, 4563, 4262, 4013]
16 [nan, np.float64(nan), 11, 'Arrears: Total mortgage accounts in arrears - over 10 yrs', 4229, 4183, 4286, 4098, 4017]
17 [nan, np.float64(nan), 'Legal Status of Accounts in Arrears', nan, nan, nan, nan, nan, nan]
18 [nan, np.float64(nan), 12, 'No Formal Demand', 25467, 23235, 21270, 21581, 20575]
19 [nan, np.float64(nan), 13, 'Formal Demand Issued', 5425, 5097, 5409, 5248, 5024]

In [4]:
print(arrears_pdh.shape)

print(
    arrears_pdh.iloc[:, 3:9].to_string(index=True)
)

(49, 9)
                                                                                                       3                    4                    5                    6                    7                    8
0                                                                                                    NaN                  NaN                  NaN                  NaN                  NaN                  NaN
1                                                                                                    PDH                  NaN                  NaN                  NaN                  NaN                  NaN
2                                                                                                    NaN                  NaN                  NaN                  NaN                  NaN            Cover_Tab
3                                                                                                    NaN        Column Labels                  NaN                  NaN                  NaN                  NaN
4                                                                                                    NaN  2025-03-31 00:00:00  2025-06-30 00:00:00  2025-09-30 00:00:00  2025-12-31 00:00:00  2026-03-31 00:00:00
5                                                                                                    Row               Number               Number               Number               Number               Number
6                                                                                                    NaN                  NaN                  NaN                  NaN                  NaN                  NaN
7                                        Outstanding Mortgages: Total mortgage loan accounts outstanding               699890               698335               698933               699968               698459
8                                                                                                    NaN                  NaN                  NaN                  NaN                  NaN                  NaN
9                                                            Arrears: Total mortgage accounts in arrears                40337                37750                36106                36253                34996
10                                           Arrears: Total mortgage accounts in arrears - up to 90 days                14455                13167                12327                13596                13694
11                                          Arrears: Total mortgage accounts in arrears - 91 to 180 days                 3345                 3123                 3013                 2952                 2681
12                                         Arrears: Total mortgage accounts in arrears - 181 to 365 days                 3769                 3416                 3199                 2998                 2814
13                            Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS)                 4136                 3867                 3522                 3285                 3040
14                                              Arrears: Total mortgage accounts in arrears - 2 to 5 yrs                 5484                 5398                 5196                 5062                 4737
15                                             Arrears: Total mortgage accounts in arrears - 5 to 10 yrs                 4919                 4596                 4563                 4262                 4013
16                                             Arrears: Total mortgage accounts in arrears - over 10 yrs                 4229                 4183                 4286                 4098                 4017
17                                                                                                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
18                                                                                      No Formal Demand                25467                23235                21270                21581                20575
19                                                                                  Formal Demand Issued                 5425                 5097                 5409                 5248                 5024
20                                                                         Legal Proceedings In Progress                 4655                 4753                 4986                 5163                 5198
21                                              Legal Proceedings Concluded (arrears remain outstanding)                 4790                 4665                 4441                 4261                 4199
22                                                                                                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
23                                                                Up to 1 year since first court hearing                 1850                 1939                 2218                 2109                 2269
24                                               Over 1 year and up to 2 years since first court hearing                  915                  968                  961                 1078                 1037
25                                              Over 2 years and up to 5 years since first court hearing                  791                  834                  839                 1014                 1030
26                                                                Over 5 years since first court hearing                 1099                 1012                  968                  962                  862
27                                                                                                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
28                           Repossessions: Residential properties in possession at beginning of quarter                  110                  114                  116                  126                  118
29                                             Repossessions: properties repossessed on foot of an order                   18                   19                   28                   13                   15
30                                           Repossessions: properties voluntarily surrendered/abandoned                    5                    8                    4                   11                   12
31                                                                    Repossessions: properties disposed                   17                   24                   19                   34                   26
32                                 Repossessions: Residential properties in possession at end of quarter                  114                  116                  126                  118                  120
33                                                                                                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
34                            Restructured Mortgages: Total mortgage accounts classified as restructured                55047                57022                56156                54948                53818
35                                                   Restructured Mortgages: of which are not in arrears                45322                47901                47524                46159                45521
36  Restructured Mortgages: Total mortgage accounts meeting the terms of current restructure arrangement                47419                49786                49480                48119                47466
37                                                                                                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
38                                                Restructured Mortgages: Interest Only - up to one year                  539                  606                  582                  548                  529
39                                                 Restructured Mortgages: Interest Only - over one year                  232                  110                  106                  109                   99
40                                     Restructured Mortgages: Reduced Payment (less than interest only)                  161                  138                  122                  117                  146
41                                  Restructured Mortgages: Reduced Payment (greater than interest only)                 1861                 1844                 1755                 1635                 1485
42                                                            Restructured Mortgages: Payment Moratorium                  479                  572                  549                  539                  514
43                                             Restructured Mortgages: Temporary Interest Rate Reduction                  799                  753                  688                  596                  452
44                                             Restructured Mortgages: Permanent Interest Rate Reduction                  199                  210                  202                  196                  249
45                                                                Restructured Mortgages: Term Extension                 8777                 8544                 8338                 8076                 7841
46                                                        Restructured Mortgages: Arrears Capitalisation                 9734                 9586                 9513                 9308                 9069
47                                                                Restructured Mortgages: Split Mortgage                20144                23302                22991                22682                22460
48                                                                         Restructured Mortgages: Other                12122                11357                11310                11142                10974

In [5]:
print(arrears_pdh.iloc[4].tolist())

[nan, np.float64(nan), nan, nan, datetime.datetime(2025, 3, 31, 0, 0), datetime.datetime(2025, 6, 30, 0, 0), datetime.datetime(2025, 9, 30, 0, 0), datetime.datetime(2025, 12, 31, 0, 0), datetime.datetime(2026, 3, 31, 0, 0)]

In [9]:
master1 = pd.read_excel(
    "../data/raw/cbi_mortgage_arrears_raw.xlsx",
    sheet_name="Master Data (1)",
    header=None
)

print(master1.shape)
master1.head(15)

(17697, 9)

,0,1,2,3,4,5,6,7,8
0,Entity Group,Format,Category,Row Position,Column Position,Row,Column,Reporting Date,Amt
1,Banks,PDH,Total Outstanding,1,1,Outstanding Mortgages: Total mortgage loan acc...,Number,2009-09-30 00:00:00,777796
2,Banks,PDH,Total Outstanding,1,2,Outstanding Mortgages: Total mortgage loan acc...,Balance € (000),2009-09-30 00:00:00,115380347
3,Banks,PDH,Arrears,2,1,Arrears: Total mortgage accounts in arrears,Number,2009-09-30 00:00:00,56868
4,Banks,PDH,Arrears,2,2,Arrears: Total mortgage accounts in arrears,Balance € (000),2009-09-30 00:00:00,9485725
5,Banks,PDH,Arrears,2,3,Arrears: Total mortgage accounts in arrears,Arrears € (000),2009-09-30 00:00:00,382919
6,Banks,PDH,Arrears,3,1,Arrears: Total mortgage accounts in arrears - ...,Number,2009-09-30 00:00:00,33791
7,Banks,PDH,Arrears,3,2,Arrears: Total mortgage accounts in arrears - ...,Balance € (000),2009-09-30 00:00:00,5392873
8,Banks,PDH,Arrears,3,3,Arrears: Total mortgage accounts in arrears - ...,Arrears € (000),2009-09-30 00:00:00,78398
9,Banks,PDH,Arrears,4,1,Arrears: Total mortgage accounts in arrears - ...,Number,2009-09-30 00:00:00,7385
10,Banks,PDH,Arrears,4,2,Arrears: Total mortgage accounts in arrears - ...,Balance € (000),2009-09-30 00:00:00,1358889
11,Banks,PDH,Arrears,4,3,Arrears: Total mortgage accounts in arrears - ...,Arrears € (000),2009-09-30 00:00:00,41836
12,Banks,PDH,Arrears,5,1,Arrears: Total mortgage accounts in arrears - ...,Number,2009-09-30 00:00:00,15692
13,Banks,PDH,Arrears,5,2,Arrears: Total mortgage accounts in arrears - ...,Balance € (000),2009-09-30 00:00:00,2733963
14,Banks,PDH,Arrears,5,3,Arrears: Total mortgage accounts in arrears - ...,Arrears € (000),2009-09-30 00:00:00,262685

In [7]:
master2 = pd.read_excel(
    "../data/raw/cbi_mortgage_arrears_raw.xlsx",
    sheet_name="Master Data (2) -Borrower Co-op",
    header=None
)

print(master2.shape)
master2.head(15)

(1513, 9)

,0,1,2,3,4,5,6,7,8
0,Entity Group,Format,Category,Row Position,Column Position,Row,Column,Reporting Date,Number of Accounts
1,Banks,PDH,Borrower co-operation status,1,1,In Arrears up to 90 days,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,5805
2,Banks,PDH,Borrower co-operation status,2,1,In Arrears 91 to 180 days,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,1993
3,Banks,PDH,Borrower co-operation status,3,1,In Arrears 181 to 365 days,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,1810
4,Banks,PDH,Borrower co-operation status,4,1,In Arrears 1 YR to 2 YR,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,1607
5,Banks,PDH,Borrower co-operation status,5,1,In Arrears 2 YR to 5 YR,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,1695
6,Banks,PDH,Borrower co-operation status,6,1,In Arrears 5 YR to 10 YR,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,466
7,Banks,PDH,Borrower co-operation status,7,1,In Arrears over 10 YRS,"Number, In Arrears, Restruc.",2019-09-30 00:00:00,111
8,Banks,PDH,Borrower co-operation status,1,2,In Arrears up to 90 days,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,7715
9,Banks,PDH,Borrower co-operation status,2,2,In Arrears 91 to 180 days,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,1165
10,Banks,PDH,Borrower co-operation status,3,2,In Arrears 181 to 365 days,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,908
11,Banks,PDH,Borrower co-operation status,4,2,In Arrears 1 YR to 2 YR,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,1081
12,Banks,PDH,Borrower co-operation status,5,2,In Arrears 2 YR to 5 YR,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,2334
13,Banks,PDH,Borrower co-operation status,6,2,In Arrears 5 YR to 10 YR,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,3212
14,Banks,PDH,Borrower co-operation status,7,2,In Arrears over 10 YRS,"Number, Not Restruc., Co-operating",2019-09-30 00:00:00,482

One important point: the master data is split by Banks and presumably Non-Banks, so we should first determine exactly how the current Central Bank Table 1 - PDH totals are constructed. We don't want to accidentally use only bank mortgages.

# Step 1 — Inspect the available entity groups

In [11]:
print(master1.head(10))
print(master1.columns)

              0       1                  2             3                4  \
0  Entity Group  Format           Category  Row Position  Column Position
1         Banks     PDH  Total Outstanding             1                1
2         Banks     PDH  Total Outstanding             1                2
3         Banks     PDH            Arrears             2                1
4         Banks     PDH            Arrears             2                2
5         Banks     PDH            Arrears             2                3
6         Banks     PDH            Arrears             3                1
7         Banks     PDH            Arrears             3                2
8         Banks     PDH            Arrears             3                3
9         Banks     PDH            Arrears             4                1

                                                   5                6  \
0                                                Row           Column
1  Outstanding Mortgages: Total mortgage loan acc...           Number
2  Outstanding Mortgages: Total mortgage loan acc...  Balance € (000)
3        Arrears: Total mortgage accounts in arrears           Number
4        Arrears: Total mortgage accounts in arrears  Balance € (000)
5        Arrears: Total mortgage accounts in arrears  Arrears € (000)
6  Arrears: Total mortgage accounts in arrears - ...           Number
7  Arrears: Total mortgage accounts in arrears - ...  Balance € (000)
8  Arrears: Total mortgage accounts in arrears - ...  Arrears € (000)
9  Arrears: Total mortgage accounts in arrears - ...           Number

                     7          8
0       Reporting Date        Amt
1  2009-09-30 00:00:00     777796
2  2009-09-30 00:00:00  115380347
3  2009-09-30 00:00:00      56868
4  2009-09-30 00:00:00    9485725
5  2009-09-30 00:00:00     382919
6  2009-09-30 00:00:00      33791
7  2009-09-30 00:00:00    5392873
8  2009-09-30 00:00:00      78398
9  2009-09-30 00:00:00       7385
Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [12]:
master1.columns = master1.iloc[0]
master1 = master1.iloc[1:].reset_index(drop=True)

print(master1.columns)
print(master1.head())

Index(['Entity Group', 'Format', 'Category', 'Row Position', 'Column Position',
       'Row', 'Column', 'Reporting Date', 'Amt'],
      dtype='object', name=0)
0 Entity Group Format           Category Row Position Column Position  \
0        Banks    PDH  Total Outstanding            1               1
1        Banks    PDH  Total Outstanding            1               2
2        Banks    PDH            Arrears            2               1
3        Banks    PDH            Arrears            2               2
4        Banks    PDH            Arrears            2               3

0                                                Row           Column  \
0  Outstanding Mortgages: Total mortgage loan acc...           Number
1  Outstanding Mortgages: Total mortgage loan acc...  Balance € (000)
2        Arrears: Total mortgage accounts in arrears           Number
3        Arrears: Total mortgage accounts in arrears  Balance € (000)
4        Arrears: Total mortgage accounts in arrears  Arrears € (000)

0       Reporting Date        Amt
0  2009-09-30 00:00:00     777796
1  2009-09-30 00:00:00  115380347
2  2009-09-30 00:00:00      56868
3  2009-09-30 00:00:00    9485725
4  2009-09-30 00:00:00     382919

In [13]:
print(master1["Entity Group"].unique())
print(master1["Format"].unique())
print(master1["Category"].unique())

<StringArray>
['Banks', 'Non-Banks']
Length: 2, dtype: str
<StringArray>
['PDH', 'BTL']
Length: 2, dtype: str
<StringArray>
[                  'Total Outstanding',                             'Arrears',
 'Legal Status of Accounts in Arrears',                       'Repossessions',
             'Restructures - Overview',              'Restructures - By Type',
       'Duration in Legal Proceedings']
Length: 7, dtype: str

we'll focus on PDH (Principal Dwelling Houses) and combine Banks + Non-Banks.

# Step 1 — Inspect the PDH arrears rows

In [14]:
arrears_rows = master1[
    (master1["Format"] == "PDH") &
    (master1["Category"] == "Arrears")
]

print(
    arrears_rows[
        ["Entity Group", "Row Position", "Row", "Column"]
    ].drop_duplicates().to_string(index=False)
)

Entity Group Row Position                                                                        Row          Column
       Banks            2                                Arrears: Total mortgage accounts in arrears          Number
       Banks            2                                Arrears: Total mortgage accounts in arrears Balance € (000)
       Banks            2                                Arrears: Total mortgage accounts in arrears Arrears € (000)
       Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days          Number
       Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days Balance € (000)
       Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days Arrears € (000)
       Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days          Number
       Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days Balance € (000)
       Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days Arrears € (000)
       Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days          Number
       Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days Balance € (000)
       Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days Arrears € (000)
       Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days          Number
       Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days Balance € (000)
       Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days Arrears € (000)
       Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS)          Number
       Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS) Balance € (000)
       Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS) Arrears € (000)
       Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS)          Number
       Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS) Balance € (000)
       Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS) Arrears € (000)
       Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs          Number
       Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs Balance € (000)
       Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs Arrears € (000)
       Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs          Number
       Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs Balance € (000)
       Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs Arrears € (000)
       Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs          Number
       Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs Balance € (000)
       Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs Arrears € (000)
   Non-Banks            2                                Arrears: Total mortgage accounts in arrears          Number
   Non-Banks            2                                Arrears: Total mortgage accounts in arrears Balance € (000)
   Non-Banks            2                                Arrears: Total mortgage accounts in arrears Arrears € (000)
   Non-Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days          Number
   Non-Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days Balance € (000)
   Non-Banks            3                Arrears: Total mortgage accounts in arrears - up to 90 days Arrears € (000)
   Non-Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days          Number
   Non-Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days Balance € (000)
   Non-Banks            4               Arrears: Total mortgage accounts in arrears - 91 to 180 days Arrears € (000)
   Non-Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days          Number
   Non-Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days Balance € (000)
   Non-Banks            5                Arrears: Total mortgage accounts in arrears - over 180 days Arrears € (000)
   Non-Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days          Number
   Non-Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days Balance € (000)
   Non-Banks            6              Arrears: Total mortgage accounts in arrears - 181 to 365 days Arrears € (000)
   Non-Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS)          Number
   Non-Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS) Balance € (000)
   Non-Banks            7 Arrears: Total mortgage accounts in arrears - 365 to 730 days (1 to 2 YRS) Arrears € (000)
   Non-Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS)          Number
   Non-Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS) Balance € (000)
   Non-Banks            8        Arrears: Total mortgage accounts in arrears - over 720 days (2 YRS) Arrears € (000)
   Non-Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs          Number
   Non-Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs Balance € (000)
   Non-Banks            9                   Arrears: Total mortgage accounts in arrears - 2 to 5 yrs Arrears € (000)
   Non-Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs          Number
   Non-Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs Balance € (000)
   Non-Banks           10                  Arrears: Total mortgage accounts in arrears - 5 to 10 yrs Arrears € (000)
   Non-Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs          Number
   Non-Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs Balance € (000)
   Non-Banks           11                  Arrears: Total mortgage accounts in arrears - over 10 yrs Arrears € (000)

In [16]:
import pandas as pd

# Make sure Amt is numeric
master1["Amt"] = pd.to_numeric(master1["Amt"], errors="coerce")

# Make sure Reporting Date is a proper date
master1["Reporting Date"] = pd.to_datetime(
    master1["Reporting Date"],
    errors="coerce"
)

# ---------------------------------------------------------
# 1. Total PDH mortgage accounts outstanding
# ---------------------------------------------------------

outstanding = master1[
    (master1["Format"] == "PDH") &
    (master1["Category"] == "Total Outstanding") &
    (master1["Column"] == "Number") &
    (master1["Entity Group"].isin(["Banks", "Non-Banks"]))
].copy()

outstanding = (
    outstanding
    .groupby("Reporting Date")["Amt"]
    .sum()
    .reset_index()
    .rename(columns={
        "Reporting Date": "date",
        "Amt": "pdh_mortgage_accounts"
    })
)


# ---------------------------------------------------------
# 2. Total PDH mortgage accounts in arrears
# ---------------------------------------------------------

total_arrears = master1[
    (master1["Format"] == "PDH") &
    (master1["Category"] == "Arrears") &
    (master1["Row Position"] == 2) &
    (master1["Column"] == "Number") &
    (master1["Entity Group"].isin(["Banks", "Non-Banks"]))
].copy()

total_arrears = (
    total_arrears
    .groupby("Reporting Date")["Amt"]
    .sum()
    .reset_index()
    .rename(columns={
        "Reporting Date": "date",
        "Amt": "pdh_arrears_accounts"
    })
)


# ---------------------------------------------------------
# 3. PDH mortgage accounts in arrears >90 days
# ---------------------------------------------------------

# These are the NON-OVERLAPPING duration categories.
arrears_90_plus_positions = [4, 6, 7, 9, 10, 11]

arrears_90_plus = master1[
    (master1["Format"] == "PDH") &
    (master1["Category"] == "Arrears") &
    (master1["Row Position"].isin(arrears_90_plus_positions)) &
    (master1["Column"] == "Number") &
    (master1["Entity Group"].isin(["Banks", "Non-Banks"]))
].copy()

arrears_90_plus = (
    arrears_90_plus
    .groupby("Reporting Date")["Amt"]
    .sum()
    .reset_index()
    .rename(columns={
        "Reporting Date": "date",
        "Amt": "pdh_arrears_90_plus_accounts"
    })
)


# ---------------------------------------------------------
# 4. Combine the three metrics
# ---------------------------------------------------------

mortgage_arrears = (
    outstanding
    .merge(total_arrears, on="date", how="outer")
    .merge(arrears_90_plus, on="date", how="outer")
    .sort_values("date")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 5. Convert account counts to integers
# ---------------------------------------------------------

count_columns = [
    "pdh_mortgage_accounts",
    "pdh_arrears_accounts",
    "pdh_arrears_90_plus_accounts"
]

for column in count_columns:
    mortgage_arrears[column] = pd.to_numeric(
        mortgage_arrears[column],
        errors="coerce"
    )


# ---------------------------------------------------------
# 6. Derived arrears percentage
# ---------------------------------------------------------

mortgage_arrears["pdh_arrears_rate"] = (
    mortgage_arrears["pdh_arrears_accounts"]
    / mortgage_arrears["pdh_mortgage_accounts"]
    * 100
)


# ---------------------------------------------------------
# 7. Derived >90-day arrears percentage
# ---------------------------------------------------------

mortgage_arrears["pdh_arrears_90_plus_rate"] = (
    mortgage_arrears["pdh_arrears_90_plus_accounts"]
    / mortgage_arrears["pdh_mortgage_accounts"]
    * 100
)


# ---------------------------------------------------------
# 8. Final column order
# ---------------------------------------------------------

mortgage_arrears = mortgage_arrears[
    [
        "date",
        "pdh_mortgage_accounts",
        "pdh_arrears_accounts",
        "pdh_arrears_90_plus_accounts",
        "pdh_arrears_rate",
        "pdh_arrears_90_plus_rate"
    ]
]


# ---------------------------------------------------------
# 9. Save processed dataset
# ---------------------------------------------------------

output_path = "../data/processed/mortgage_arrears.csv"

mortgage_arrears.to_csv(
    output_path,
    index=False
)

print("Processed mortgage arrears data saved to:", output_path)
print("Shape:", mortgage_arrears.shape)
print()
print(mortgage_arrears.head())
print()
print(mortgage_arrears.tail())

Processed mortgage arrears data saved to: ../data/processed/mortgage_arrears.csv
Shape: (67, 6)

        date  pdh_mortgage_accounts  pdh_arrears_accounts  \
0 2009-09-30                 794609                 63619
1 2009-12-31                 792885                 69647
2 2010-03-31                 791047                 76100
3 2010-06-30                 789814                 82377
4 2010-09-30                 788745                 86362

   pdh_arrears_90_plus_accounts  pdh_arrears_rate  pdh_arrears_90_plus_rate
0                          8504          8.006328                  1.070212
1                          9418          8.783998                  1.187814
2                         10504          9.620162                  1.327860
3                         11641         10.429924                  1.473891
4                         12423         10.949293                  1.575034

         date  pdh_mortgage_accounts  pdh_arrears_accounts  \
62 2025-03-31                 699890                 40337
63 2025-06-30                 698335                 37750
64 2025-09-30                 698933                 36106
65 2025-12-31                 699968                 36253
66 2026-03-31                 698459                 34996

    pdh_arrears_90_plus_accounts  pdh_arrears_rate  pdh_arrears_90_plus_rate
62                         25882          5.763334                  3.698010
63                         24583          5.405715                  3.520230
64                         23779          5.165874                  3.402186
65                         22657          5.179237                  3.236862
66                         21302          5.010459                  3.049857

# 2 validate

In [17]:
print("Rows:", len(mortgage_arrears))
print("Missing values:")
print(mortgage_arrears.isna().sum())

print()
print("Duplicate dates:", mortgage_arrears["date"].duplicated().sum())

print()
print("Date range:")
print(mortgage_arrears["date"].min())
print(mortgage_arrears["date"].max())

print()
print("Latest observation:")
print(mortgage_arrears.tail(1).to_string(index=False))

Rows: 67
Missing values:
date                            0
pdh_mortgage_accounts           0
pdh_arrears_accounts            0
pdh_arrears_90_plus_accounts    0
pdh_arrears_rate                0
pdh_arrears_90_plus_rate        0
dtype: int64

Duplicate dates: 0

Date range:
2009-09-30 00:00:00
2026-03-31 00:00:00

Latest observation:
      date  pdh_mortgage_accounts  pdh_arrears_accounts  pdh_arrears_90_plus_accounts  pdh_arrears_rate  pdh_arrears_90_plus_rate
2026-03-31                 698459                 34996                         21302          5.010459                  3.049857

In [18]:
print(
    mortgage_arrears[
        mortgage_arrears["date"] == "2026-03-31"
    ].to_string(index=False)
)

      date  pdh_mortgage_accounts  pdh_arrears_accounts  pdh_arrears_90_plus_accounts  pdh_arrears_rate  pdh_arrears_90_plus_rate
2026-03-31                 698459                 34996                         21302          5.010459                  3.049857